version: '3.8'
services:
  mdd_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'oc_mdd-app_db'
      MYSQL_USER: 'oc_user'
      MYSQL_PASSWORD: 'oc_pwd'
      MYSQL_ROOT_PASSWORD: 'oc_pwd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./resources/sql/script.sql:/docker-entrypoint-initdb.d/script.sql

  # frontend:
  #   container_name: front-end-container  # Container name
  #   build: ./ # Location of our Dockerfile
  #   volumes:  # Volume binding
  #     - './front:/usr/src/app' 
  #   ports: 
  #     - '4200:4201'  # Port mapping
  #   command: > 
  #     bash -c "npm install && ng serve --host 0.0.0.0 --port 4201"